pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                bat 'mvn clean'
            }
        }

        stage('Execute Tests') {
            steps {
                bat 'mvn test'
            }
        }

    }
}